### PR TITLE
Update content.js

### PR DESCRIPTION
**Pull request by cognitive137**
Updated lookup table.

### CODE REVIEW

**Comment by acagastya** [comment]
Hi, thanks for this PR.

As I understand you have added the feature to support Deutsche Welle.  Consider this article: <https://www.dw.com/en/coronavirus-vaccine-uk-rollout/a-55860312>.  It does not have any author listed.  Therefore, this will fail:

```js
author = strongElements.filter(el => el.innerText == "Author")[0].parentElement.innerText.replace("Author ", "");
```

That is because `strongElements.filter(el => el.innerText == "Author")` will return `[]`.  Therefore, I suggest you update that line to either one of the two.

## 1
```diff
-author = strongElements.filter(el => el.innerText == "Author")[0].parentElement.innerText.replace("Author ", "");
+author = strongElements.filter(el => el.innerText == "Author")[0]?.parentElement.innerText.replace("Author ", "") || "";
```

## 2
```diff
-author = strongElements.filter(el => el.innerText == "Author")[0].parentElement.innerText.replace("Author ", "");
+author = strongElements.filter(el => el.innerText == "Author").length ? strongElements.filter(el => el.innerText == "Author")[0].parentElement.innerText.replace("Author ", "")  :  "";
```

The first one uses optional chaining.  ([Read about it on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining))

The second one will work on old JavaScript engines too.  Attempt has been made to keep things at ES6, but whatever you prefer.

Please note, this was tested on Brave browser which runs on V8 engine.

**Review by acagastya — COMMENTED** [review]
Hi, thanks for this PR.  Could you please read the detailed explanation [here](https://github.com/acagastya/ext-wn-sources/pull/1#issuecomment-740511510)?

**Comment by cognitive137** [comment]
I don't think that line is there, the line that needs to be edited.
Or am I missing something?

**Comment by acagastya** [comment]
See the selected text: Screenshot 2020-12-08 at 15 42 47

**Comment by cognitive137** [comment]
Updated.

**Comment by acagastya** [comment]
There is a typo there (because of my original typo).
```diff
-: parentElement.innerText.replace("Author ", "");
+: "";
```

Can you please fix that so I can test and merge, @cognitive137?

**Comment by cognitive137** [comment]
Updated.

**Comment by acagastya** [comment]
Works like a charm!  Thanks.

**Pull request merged**
